CREATE DATABASE AUTOMACAO;


CREATE TABLE MONITORA_ROBO(
    IDROBO INT PRIMARY KEY AUTO_INCREMENT,
    ROBO VARCHAR(30) NOT NULL,
    TIPO_SERVICO VARCHAR(30) NOT NULL,
    STATUS INT(1) NOT NULL,
    ULTIMA_ATT DATETIME NOT NULL,
    ULTIMA_MUD DATETIME NOT NULL,
    IPSERVIDOR VARCHAR(20) NOT NULL,
    MAC CHAR(17) NOT NULL UNIQUE,
    RST INT
);